# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vecdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vecdb.proto',
  package='vecdb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bvecdb.proto\x12\x05vecdb\"\x17\n\nvectorType\x12\t\n\x01\x65\x18\x01 \x03(\x02\"P\n\rsingleDocType\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12!\n\x06vector\x18\x02 \x01(\x0b\x32\x11.vecdb.vectorType\x12\x0f\n\x07\x62\x36\x34\x64\x61ta\x18\x03 \x01(\x0c\"8\n\raddDocRequest\x12\'\n\tdocuments\x18\x01 \x03(\x0b\x32\x14.vecdb.singleDocType\"-\n\x0e\x61\x64\x64\x44ocResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03_id\x18\x02 \x03(\t\";\n\x10\x64\x65leteDocRequest\x12\'\n\tdocuments\x18\x01 \x03(\x0b\x32\x14.vecdb.singleDocType\"0\n\x11\x64\x65leteDocResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03_id\x18\x02 \x03(\t\"\x1f\n\x0e\x61\x64\x64NodeRequest\x12\r\n\x05peers\x18\x01 \x03(\t\"0\n\x0f\x61\x64\x64NodeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\r\n\x05peers\x18\x02 \x03(\t\"A\n\x11getNearestRequest\x12!\n\x06matrix\x18\x01 \x03(\x0b\x32\x11.vecdb.vectorType\x12\t\n\x01k\x18\x02 \x01(\x05\"L\n\x12getNearestResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x13\n\x0b\x64ist_matrix\x18\x02 \x01(\x0c\x12\x11\n\tdocuments\x18\x03 \x01(\x0c\x32\x8e\x02\n\x0cVecdbService\x12;\n\x0c\x61\x64\x64\x44ocuments\x12\x14.vecdb.addDocRequest\x1a\x15.vecdb.addDocResponse\x12\x44\n\x0f\x64\x65leteDocuments\x12\x17.vecdb.deleteDocRequest\x1a\x18.vecdb.deleteDocResponse\x12\x38\n\x07\x61\x64\x64Node\x12\x15.vecdb.addNodeRequest\x1a\x16.vecdb.addNodeResponse\x12\x41\n\ngetNearest\x12\x18.vecdb.getNearestRequest\x1a\x19.vecdb.getNearestResponseb\x06proto3')
)




_VECTORTYPE = _descriptor.Descriptor(
  name='vectorType',
  full_name='vecdb.vectorType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='vecdb.vectorType.e', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=45,
)


_SINGLEDOCTYPE = _descriptor.Descriptor(
  name='singleDocType',
  full_name='vecdb.singleDocType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='vecdb.singleDocType._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='vecdb.singleDocType.vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b64data', full_name='vecdb.singleDocType.b64data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=127,
)


_ADDDOCREQUEST = _descriptor.Descriptor(
  name='addDocRequest',
  full_name='vecdb.addDocRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documents', full_name='vecdb.addDocRequest.documents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=185,
)


_ADDDOCRESPONSE = _descriptor.Descriptor(
  name='addDocResponse',
  full_name='vecdb.addDocResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='vecdb.addDocResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='vecdb.addDocResponse._id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=232,
)


_DELETEDOCREQUEST = _descriptor.Descriptor(
  name='deleteDocRequest',
  full_name='vecdb.deleteDocRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documents', full_name='vecdb.deleteDocRequest.documents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=293,
)


_DELETEDOCRESPONSE = _descriptor.Descriptor(
  name='deleteDocResponse',
  full_name='vecdb.deleteDocResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='vecdb.deleteDocResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='vecdb.deleteDocResponse._id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=343,
)


_ADDNODEREQUEST = _descriptor.Descriptor(
  name='addNodeRequest',
  full_name='vecdb.addNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers', full_name='vecdb.addNodeRequest.peers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=376,
)


_ADDNODERESPONSE = _descriptor.Descriptor(
  name='addNodeResponse',
  full_name='vecdb.addNodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='vecdb.addNodeResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peers', full_name='vecdb.addNodeResponse.peers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=426,
)


_GETNEARESTREQUEST = _descriptor.Descriptor(
  name='getNearestRequest',
  full_name='vecdb.getNearestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='vecdb.getNearestRequest.matrix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='vecdb.getNearestRequest.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=493,
)


_GETNEARESTRESPONSE = _descriptor.Descriptor(
  name='getNearestResponse',
  full_name='vecdb.getNearestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='vecdb.getNearestResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_matrix', full_name='vecdb.getNearestResponse.dist_matrix', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='documents', full_name='vecdb.getNearestResponse.documents', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=571,
)

_SINGLEDOCTYPE.fields_by_name['vector'].message_type = _VECTORTYPE
_ADDDOCREQUEST.fields_by_name['documents'].message_type = _SINGLEDOCTYPE
_DELETEDOCREQUEST.fields_by_name['documents'].message_type = _SINGLEDOCTYPE
_GETNEARESTREQUEST.fields_by_name['matrix'].message_type = _VECTORTYPE
DESCRIPTOR.message_types_by_name['vectorType'] = _VECTORTYPE
DESCRIPTOR.message_types_by_name['singleDocType'] = _SINGLEDOCTYPE
DESCRIPTOR.message_types_by_name['addDocRequest'] = _ADDDOCREQUEST
DESCRIPTOR.message_types_by_name['addDocResponse'] = _ADDDOCRESPONSE
DESCRIPTOR.message_types_by_name['deleteDocRequest'] = _DELETEDOCREQUEST
DESCRIPTOR.message_types_by_name['deleteDocResponse'] = _DELETEDOCRESPONSE
DESCRIPTOR.message_types_by_name['addNodeRequest'] = _ADDNODEREQUEST
DESCRIPTOR.message_types_by_name['addNodeResponse'] = _ADDNODERESPONSE
DESCRIPTOR.message_types_by_name['getNearestRequest'] = _GETNEARESTREQUEST
DESCRIPTOR.message_types_by_name['getNearestResponse'] = _GETNEARESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vectorType = _reflection.GeneratedProtocolMessageType('vectorType', (_message.Message,), dict(
  DESCRIPTOR = _VECTORTYPE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.vectorType)
  ))
_sym_db.RegisterMessage(vectorType)

singleDocType = _reflection.GeneratedProtocolMessageType('singleDocType', (_message.Message,), dict(
  DESCRIPTOR = _SINGLEDOCTYPE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.singleDocType)
  ))
_sym_db.RegisterMessage(singleDocType)

addDocRequest = _reflection.GeneratedProtocolMessageType('addDocRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDDOCREQUEST,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.addDocRequest)
  ))
_sym_db.RegisterMessage(addDocRequest)

addDocResponse = _reflection.GeneratedProtocolMessageType('addDocResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDDOCRESPONSE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.addDocResponse)
  ))
_sym_db.RegisterMessage(addDocResponse)

deleteDocRequest = _reflection.GeneratedProtocolMessageType('deleteDocRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDOCREQUEST,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.deleteDocRequest)
  ))
_sym_db.RegisterMessage(deleteDocRequest)

deleteDocResponse = _reflection.GeneratedProtocolMessageType('deleteDocResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDOCRESPONSE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.deleteDocResponse)
  ))
_sym_db.RegisterMessage(deleteDocResponse)

addNodeRequest = _reflection.GeneratedProtocolMessageType('addNodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDNODEREQUEST,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.addNodeRequest)
  ))
_sym_db.RegisterMessage(addNodeRequest)

addNodeResponse = _reflection.GeneratedProtocolMessageType('addNodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDNODERESPONSE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.addNodeResponse)
  ))
_sym_db.RegisterMessage(addNodeResponse)

getNearestRequest = _reflection.GeneratedProtocolMessageType('getNearestRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNEARESTREQUEST,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.getNearestRequest)
  ))
_sym_db.RegisterMessage(getNearestRequest)

getNearestResponse = _reflection.GeneratedProtocolMessageType('getNearestResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNEARESTRESPONSE,
  __module__ = 'vecdb_pb2'
  # @@protoc_insertion_point(class_scope:vecdb.getNearestResponse)
  ))
_sym_db.RegisterMessage(getNearestResponse)



_VECDBSERVICE = _descriptor.ServiceDescriptor(
  name='VecdbService',
  full_name='vecdb.VecdbService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=574,
  serialized_end=844,
  methods=[
  _descriptor.MethodDescriptor(
    name='addDocuments',
    full_name='vecdb.VecdbService.addDocuments',
    index=0,
    containing_service=None,
    input_type=_ADDDOCREQUEST,
    output_type=_ADDDOCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteDocuments',
    full_name='vecdb.VecdbService.deleteDocuments',
    index=1,
    containing_service=None,
    input_type=_DELETEDOCREQUEST,
    output_type=_DELETEDOCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addNode',
    full_name='vecdb.VecdbService.addNode',
    index=2,
    containing_service=None,
    input_type=_ADDNODEREQUEST,
    output_type=_ADDNODERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getNearest',
    full_name='vecdb.VecdbService.getNearest',
    index=3,
    containing_service=None,
    input_type=_GETNEARESTREQUEST,
    output_type=_GETNEARESTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VECDBSERVICE)

DESCRIPTOR.services_by_name['VecdbService'] = _VECDBSERVICE

# @@protoc_insertion_point(module_scope)
