FROM node:16-alpine

WORKDIR /app

COPY . .

RUN yarn

CMD export NEXT_PUBLIC_AQUILA_API_URL=$NEXT_PUBLIC_AQUILA_API_URL_BUILD && yarn build && export NEXT_PUBLIC_AQUILA_API_URL=$NEXT_PUBLIC_AQUILA_API_URL_DEPLOYMENT && yarn start
