FROM node:16-alpine

ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG NEXT_PUBLIC_AQUILA_API_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NODE_ENV=production

WORKDIR /app

COPY . .

ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXT_PUBLIC_AQUILA_API_URL=$NEXT_PUBLIC_AQUILA_API_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

RUN yarn

RUN NODE_ENV=${NODE_ENV} yarn build

EXPOSE 3000

CMD ["yarn", "start"]