# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/faiss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/faiss.proto',
  package='faiss',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11proto/faiss.proto\x12\x05\x66\x61iss\"\x17\n\nvectorType\x12\t\n\x01\x65\x18\x01 \x03(\x02\">\n\x0c\x64ocumentType\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12!\n\x06vector\x18\x02 \x01(\x0b\x32\x11.faiss.vectorType\"{\n\x10initFaissRequest\x12\r\n\x05nlist\x18\x01 \x01(\x05\x12\x0e\n\x06nprobe\x18\x02 \x01(\x05\x12\x0b\n\x03\x62pv\x18\x03 \x01(\x05\x12\x0c\n\x04\x62psv\x18\x04 \x01(\x05\x12\n\n\x02vd\x18\x05 \x01(\x05\x12!\n\x06matrix\x18\x06 \x03(\x0b\x32\x11.faiss.vectorType\"#\n\x11initFaissResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"7\n\raddVecRequest\x12&\n\tdocuments\x18\x01 \x03(\x0b\x32\x13.faiss.documentType\"-\n\x0e\x61\x64\x64VecResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03_id\x18\x02 \x03(\t\"\x1f\n\x10\x64\x65leteVecRequest\x12\x0b\n\x03_id\x18\x02 \x03(\t\"0\n\x11\x64\x65leteVecResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03_id\x18\x02 \x03(\t\"A\n\x11getNearestRequest\x12!\n\x06matrix\x18\x01 \x03(\x0b\x32\x11.faiss.vectorType\x12\t\n\x01k\x18\x02 \x01(\x05\"F\n\x12getNearestResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03ids\x18\x02 \x01(\t\x12\x13\n\x0b\x64ist_matrix\x18\x03 \x01(\t2\x90\x02\n\x0c\x46\x61issService\x12>\n\tinitFaiss\x12\x17.faiss.initFaissRequest\x1a\x18.faiss.initFaissResponse\x12\x39\n\naddVectors\x12\x14.faiss.addVecRequest\x1a\x15.faiss.addVecResponse\x12\x42\n\rdeleteVectors\x12\x17.faiss.deleteVecRequest\x1a\x18.faiss.deleteVecResponse\x12\x41\n\ngetNearest\x12\x18.faiss.getNearestRequest\x1a\x19.faiss.getNearestResponseb\x06proto3')
)




_VECTORTYPE = _descriptor.Descriptor(
  name='vectorType',
  full_name='faiss.vectorType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='faiss.vectorType.e', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_DOCUMENTTYPE = _descriptor.Descriptor(
  name='documentType',
  full_name='faiss.documentType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='faiss.documentType._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='faiss.documentType.vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=115,
)


_INITFAISSREQUEST = _descriptor.Descriptor(
  name='initFaissRequest',
  full_name='faiss.initFaissRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nlist', full_name='faiss.initFaissRequest.nlist', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nprobe', full_name='faiss.initFaissRequest.nprobe', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bpv', full_name='faiss.initFaissRequest.bpv', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bpsv', full_name='faiss.initFaissRequest.bpsv', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vd', full_name='faiss.initFaissRequest.vd', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matrix', full_name='faiss.initFaissRequest.matrix', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=240,
)


_INITFAISSRESPONSE = _descriptor.Descriptor(
  name='initFaissResponse',
  full_name='faiss.initFaissResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='faiss.initFaissResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=277,
)


_ADDVECREQUEST = _descriptor.Descriptor(
  name='addVecRequest',
  full_name='faiss.addVecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documents', full_name='faiss.addVecRequest.documents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=334,
)


_ADDVECRESPONSE = _descriptor.Descriptor(
  name='addVecResponse',
  full_name='faiss.addVecResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='faiss.addVecResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='faiss.addVecResponse._id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=381,
)


_DELETEVECREQUEST = _descriptor.Descriptor(
  name='deleteVecRequest',
  full_name='faiss.deleteVecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='faiss.deleteVecRequest._id', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=414,
)


_DELETEVECRESPONSE = _descriptor.Descriptor(
  name='deleteVecResponse',
  full_name='faiss.deleteVecResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='faiss.deleteVecResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_id', full_name='faiss.deleteVecResponse._id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=464,
)


_GETNEARESTREQUEST = _descriptor.Descriptor(
  name='getNearestRequest',
  full_name='faiss.getNearestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='faiss.getNearestRequest.matrix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='faiss.getNearestRequest.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=531,
)


_GETNEARESTRESPONSE = _descriptor.Descriptor(
  name='getNearestResponse',
  full_name='faiss.getNearestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='faiss.getNearestResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ids', full_name='faiss.getNearestResponse.ids', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_matrix', full_name='faiss.getNearestResponse.dist_matrix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=603,
)

_DOCUMENTTYPE.fields_by_name['vector'].message_type = _VECTORTYPE
_INITFAISSREQUEST.fields_by_name['matrix'].message_type = _VECTORTYPE
_ADDVECREQUEST.fields_by_name['documents'].message_type = _DOCUMENTTYPE
_GETNEARESTREQUEST.fields_by_name['matrix'].message_type = _VECTORTYPE
DESCRIPTOR.message_types_by_name['vectorType'] = _VECTORTYPE
DESCRIPTOR.message_types_by_name['documentType'] = _DOCUMENTTYPE
DESCRIPTOR.message_types_by_name['initFaissRequest'] = _INITFAISSREQUEST
DESCRIPTOR.message_types_by_name['initFaissResponse'] = _INITFAISSRESPONSE
DESCRIPTOR.message_types_by_name['addVecRequest'] = _ADDVECREQUEST
DESCRIPTOR.message_types_by_name['addVecResponse'] = _ADDVECRESPONSE
DESCRIPTOR.message_types_by_name['deleteVecRequest'] = _DELETEVECREQUEST
DESCRIPTOR.message_types_by_name['deleteVecResponse'] = _DELETEVECRESPONSE
DESCRIPTOR.message_types_by_name['getNearestRequest'] = _GETNEARESTREQUEST
DESCRIPTOR.message_types_by_name['getNearestResponse'] = _GETNEARESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vectorType = _reflection.GeneratedProtocolMessageType('vectorType', (_message.Message,), dict(
  DESCRIPTOR = _VECTORTYPE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.vectorType)
  ))
_sym_db.RegisterMessage(vectorType)

documentType = _reflection.GeneratedProtocolMessageType('documentType', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTTYPE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.documentType)
  ))
_sym_db.RegisterMessage(documentType)

initFaissRequest = _reflection.GeneratedProtocolMessageType('initFaissRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITFAISSREQUEST,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.initFaissRequest)
  ))
_sym_db.RegisterMessage(initFaissRequest)

initFaissResponse = _reflection.GeneratedProtocolMessageType('initFaissResponse', (_message.Message,), dict(
  DESCRIPTOR = _INITFAISSRESPONSE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.initFaissResponse)
  ))
_sym_db.RegisterMessage(initFaissResponse)

addVecRequest = _reflection.GeneratedProtocolMessageType('addVecRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDVECREQUEST,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.addVecRequest)
  ))
_sym_db.RegisterMessage(addVecRequest)

addVecResponse = _reflection.GeneratedProtocolMessageType('addVecResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDVECRESPONSE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.addVecResponse)
  ))
_sym_db.RegisterMessage(addVecResponse)

deleteVecRequest = _reflection.GeneratedProtocolMessageType('deleteVecRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEVECREQUEST,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.deleteVecRequest)
  ))
_sym_db.RegisterMessage(deleteVecRequest)

deleteVecResponse = _reflection.GeneratedProtocolMessageType('deleteVecResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEVECRESPONSE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.deleteVecResponse)
  ))
_sym_db.RegisterMessage(deleteVecResponse)

getNearestRequest = _reflection.GeneratedProtocolMessageType('getNearestRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNEARESTREQUEST,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.getNearestRequest)
  ))
_sym_db.RegisterMessage(getNearestRequest)

getNearestResponse = _reflection.GeneratedProtocolMessageType('getNearestResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNEARESTRESPONSE,
  __module__ = 'proto.faiss_pb2'
  # @@protoc_insertion_point(class_scope:faiss.getNearestResponse)
  ))
_sym_db.RegisterMessage(getNearestResponse)



_FAISSSERVICE = _descriptor.ServiceDescriptor(
  name='FaissService',
  full_name='faiss.FaissService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=606,
  serialized_end=878,
  methods=[
  _descriptor.MethodDescriptor(
    name='initFaiss',
    full_name='faiss.FaissService.initFaiss',
    index=0,
    containing_service=None,
    input_type=_INITFAISSREQUEST,
    output_type=_INITFAISSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addVectors',
    full_name='faiss.FaissService.addVectors',
    index=1,
    containing_service=None,
    input_type=_ADDVECREQUEST,
    output_type=_ADDVECRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteVectors',
    full_name='faiss.FaissService.deleteVectors',
    index=2,
    containing_service=None,
    input_type=_DELETEVECREQUEST,
    output_type=_DELETEVECRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getNearest',
    full_name='faiss.FaissService.getNearest',
    index=3,
    containing_service=None,
    input_type=_GETNEARESTREQUEST,
    output_type=_GETNEARESTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAISSSERVICE)

DESCRIPTOR.services_by_name['FaissService'] = _FAISSSERVICE

# @@protoc_insertion_point(module_scope)
